### ISSUE TITLE
Callbacks for ResourceLoadEvent fail to deserialize

### ISSUE THREAD

**Issue by zombiezen** [koute/stdweb#171]
## Reproduction Case

I'm unable to capture an onload event for images using WebAssembly.

```rust
#[macro_use]
extern crate stdweb;

use stdweb::web::IEventTarget;
use stdweb::web::event::ResourceLoadEvent;
use stdweb::web::html_element::ImageElement;

fn main() {
    ::std::panic::set_hook(Box::new(|info| {
        console!(error, format!("!!! RUST PANIC !!! {:?}", info));
    }));
    let elem = ImageElement::new();
    elem.add_event_listener(|_evt: ResourceLoadEvent| {
        console!(log, "loaded");
    });
    elem.set_src("image.png");
}
```

## Expected Console Output

```
loaded
```

## Actual Output

```
!!! RUST PANIC !!! PanicInfo { payload: Any, message: Some(Argument #1 is not convertible to '<Rust type>'), location: Location { file: "/home/light/.cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.2/src/webcore/serialization.rs", line: 1179, col: 1 } }
wasm-0004b76e-40:1357 Uncaught RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h528b9a7d2e2b71f3 (wasm-function[40]:2825)
    at std::panicking::begin_panic_fmt::h89af9c3bb77d7611 (wasm-function[85]:255)
    at <stdweb::webcore::newtype::Newtype<(stdweb::webcore::serialization::FunctionTag, (A12,)), F> as stdweb::webcore::serialization::FuncallAdapter<F>>::funcall_adapter::h758ab61ca932d882 (wasm-function[13]:1379)
    at Object.Module.STDWEB_PRIVATE.dyncall (http://localhost:8000/stdwebrepro.js:379:40)
    at Image.output (http://localhost:8000/stdwebrepro.js:116:35)
```

## Relevant Versions

- stdweb 0.4.2
- rustc 1.26.0-nightly (0ff9872b2 2018-02-28), compiling for wasm32-unknown-unknown
- cargo-web 0.6.8
- Chrome 65.0.3325.181 64-bit Windows

**Comment by koute** [comment]
Thanks for the terrific report!

This happens because our `ResourceLoadEvent` derives from `UIEvent`, while the event which is sent here is only an `Event`. An unfortunate consequence of the fact that there are actually multiple different events which are *all* `"load"` events.

I'm still not entirely sure what to do here, but I guess we'll need two separate events of this kind - one deriving from `UIEvent`, and one only from `Event`. The question is though - which one is more common? The specs say that the type of these events is "UIEvent if generated from a user interface, Event otherwise.", but I have a hard time finding a more detailed explanation as to when an event is treated as being generated from a user interface. (It's late; maybe I'm just blind.) Anyone knows?

**Comment by kuviman** [comment]
Since [`UIEvent` is an `Event`](https://www.w3.org/TR/DOM-Level-3-Events/#uievent-uievent):

    interface UIEvent : Event

These events are always `Event`, and are only `UIEvent` sometimes, right?

Maybe it is ok to derive `ResourceLoadEvent`, `ResourceAbortEvent` and `ResourceErrorEvent` from `Event`?

I don't know if it is useful to treat them as `UIEvent` anyway, I think a typical handler doesn't use the event object at all actually.

**Comment by vitiral** [comment]
I don't know if this is related at all, but I hit a similar issue when trying to use `js!` to handle the `load` event:

```
        let rs_handle = move || {
            callback2.emit(RouteInfo::new(Value::Null));
        };
        self.handle2 = Some(js!{
            // FIXME: for some _bizare_ reason defining `action` is necessary here...
            function action() { @{rs_handle()} };
            window.addEventListener("load", action);
            return action;
            // What I want to do is this:
            // var handle = @{rs_handle};
            // window.addEventListener("load", handle);
            // return handle;
        });
```

**Comment by Pauan** [comment]
@vitiral Your code is a bit wrong:

```rust
function action() { @{rs_handle()} };
```

That needs to be like this:

```rust
function action() { @{rs_handle}() };
```

As for the error, that's completely intentional. Rust is statically typed, and it doesn't have optional arguments, so if you pass in the wrong number of arguments then it *should* error. Therefore it is sometimes necessary to create JS shim functions.

In the case of event listeners, it's common to use code like this:

```rust
let rs_handle = move || {
    callback2.emit(RouteInfo::new(Value::Null));
};

self.handle2 = Some(js!{
    var callback = @{rs_handle};

    function listener() {
        callback();
    }

    window.addEventListener("load", listener);

    return {
        callback: callback,
        listener: listener
    };
});
```

And now it's possible to write a correct `Drop` implementation:

```rust
impl Drop for ... {
    fn drop(&mut self) {
        if let Some(ref handle2) = self.handle2 {
            js! { @(no_return)
                var handle = @{handle2};
                window.removeEventListener("load", handle.listener);
                handle.callback.drop();
            }
        }
    }
}
```

**Comment by vitiral** [comment]
@Pauan I tried both ways (both work). Thanks for the tip on doing drop correctly.

I guess I'm confused... the `function listener()` you defined is in javascript but also doesn't have optional arguments... why wouldn't you get the same error (or a corresponding javascript error) if multiple arguments are being passed in?

... and I have the answer:

https://www.w3schools.com/js/js_function_parameters.asp
```
function findMax() {
    var i;
    var max = -Infinity;
    for (i = 0; i < arguments.length; i++) {
        if (arguments[i] > max) {
            max = arguments[i];
        }
    }
    return max;
}
```

What amazing design!

**Comment by Pauan** [comment]
@vitiral Yes, Rust closures require an exact number of arguments, but JavaScript functions can accept an unlimited number of arguments (in addition, arguments are *always* optional in JavaScript), which is why it works if you use a JavaScript function shim.
