### ISSUE TITLE
exception thrown: TypeError: Cannot read property 'from_js' of undefined,TypeError: Cannot read property 'from_js' of undefined

### ISSUE THREAD

**Issue by greyblake** [koute/stdweb#41]
Thank you for the library, it looks very exiting! Unfortunately I am getting an error, trying to run a very simple example.

Here is my `src/main.rs`:

```rust
#[macro_use]
extern crate stdweb;

fn main() {
    let message = "Saluton";
    js! {
        alert( @{message} );
    };
}
```
In browser (both Chromium and the latest Firefox) I am getting the following errors:
```
http://[::1]:8000/js/app.js:190 exception thrown: TypeError: Cannot read property 'from_js' of undefined,TypeError: Cannot read property 'from_js' of undefined
    at Array.ASM_CONSTS (http://[::1]:8000/js/app.js:1602:35)
    at _emscripten_asm_const_iii (http://[::1]:8000/js/app.js:1609:26)
    at Array.__ZN6tryweb4main17he5640be6c1e443adE (http://[::1]:8000/js/app.js:8108:11)
    at __ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17hf69b2510974d151bE (http://[::1]:8000/js/app.js:17305:28)
    at Array.__ZN3std9panicking3try7do_call17hc7f54292c4f8bc7dE_llvm_E2C4E477 (http://[::1]:8000/js/app.js:15004:2)
    at Object.dynCall_vi (http://[::1]:8000/js/app.js:37926:31)
    at invoke_vi (http://[::1]:8000/js/app.js:5322:25)
    at ___rust_maybe_catch_panic (http://[::1]:8000/js/app.js:24679:2)
    at __ZN3std2rt10lang_start17h24169098a28de597E (http://[::1]:8000/js/app.js:12472:9)
    at _main (http://[::1]:8000/js/app.js:8032:8)
```

However `println!("message")` results into normal console log message.

Extra details:
* browser - the latest firefox
* I run the app with `cargo web start`
* rustc 1.24.0-nightly (dc39c3169 2017-12-17)

**Comment by koute** [comment]
You are missing a call to [event_loop](https://docs.rs/stdweb/0.2.0/stdweb/fn.event_loop.html) at the end of your `main` which is required under Emscripten backends. (: 

Either add a call to `event_loop` or pass `--target-webasm` argument to `cargo-web` to use Rust's native webassembly backend which doesn't use Emscripten.

**Comment by greyblake** [comment]
@koute thank you!

I guess I also missed `stdweb::initialize();` (based on the [example](https://github.com/koute/stdweb/blob/master/examples/minimal/src/main.rs)]
Would it make sense to add this to the first example in README? (I can open PR if necessary)

**Comment by koute** [comment]
> Would it make sense to add this to the first example in README? (I can open PR if necessary)

Hmmmm.... I'm not sure! The examples section is meant to be more of a demo of the library's capabilities rather than actual documentation, and *technically* we **do** have `examples/minimal` where the correct usage is shown. Perhaps a remark which urged the reader to take a look at that example would be more appropriate?

**Comment by AndrewGaspar** [comment]
@koute I just ran into this. I personally think it would be a good idea to show calling `stdweb::initialize()` in the README, but of course that's because I hit the same bug. Thankfully searching the GitHub brought me right to this issue. :)
