### ISSUE TITLE
All requests to /js/app.js return ERR_ABORTED

### ISSUE THREAD

**Issue by iirelu** [koute/stdweb#70]
![screenshot from 2018-01-10 09-30-05](https://user-images.githubusercontent.com/3432543/34762681-e50720b2-f5e8-11e7-9adb-14486862312c.png)

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0:     0x5603f5c83c1b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h9d1ecf383d3d35dd
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x5603f5c90ee1 - std::sys_common::backtrace::print::h377b6336f9bd7acd
                               at libstd/sys_common/backtrace.rs:68
                               at libstd/sys_common/backtrace.rs:57
   2:     0x5603f5c7d770 - std::panicking::default_hook::{{closure}}::hd8ba10fcaf3b3605
                               at libstd/panicking.rs:381
   3:     0x5603f5c7d2ac - std::panicking::default_hook::hdadaf36afc2164e8
                               at libstd/panicking.rs:397
   4:     0x5603f5c7dbbb - std::panicking::rust_panic_with_hook::h856923614f259da2
                               at libstd/panicking.rs:577
   5:     0x5603f5c7da7e - std::panicking::begin_panic::he19efc0e8b16f633
                               at libstd/panicking.rs:538
   6:     0x5603f5c7d97a - std::panicking::begin_panic_fmt::hb84c3f6aa82e7f67
                               at libstd/panicking.rs:522
   7:     0x5603f5c7d912 - rust_begin_unwind
                               at libstd/panicking.rs:498
   8:     0x5603f5ce6390 - core::panicking::panic_fmt::h87b8697e64f0b225
                               at libcore/panicking.rs:71
   9:     0x5603f5ce62b6 - core::panicking::panic::h3b1a363ecbf0c21e
                               at libcore/panicking.rs:51
  10:     0x5603f59d452b - std::panicking::try::do_call::h8ce8770ad1f897e6
  11:     0x5603f5ca7f4e - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  12:     0x5603f58d9ce5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3820d78ead11dfb3
  13:     0x5603f59d5ae5 - std::panicking::try::do_call::hc6a70fb34c59ed0c
  14:     0x5603f5ca7f4e - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  15:     0x5603f598dc9a - <F as alloc::boxed::FnBox<A>>::call_box::h2ec1464b64f0c2e3
  16:     0x5603f5c8d247 - std::sys_common::thread::start_thread::hdbe346086586a07c
                               at /checkout/src/liballoc/boxed.rs:827
                               at libstd/sys_common/thread.rs:24
  17:     0x5603f5c7e228 - std::sys::unix::thread::Thread::new::thread_start::h780b8fb895b899ad
                               at libstd/sys/unix/thread.rs:90
  18:     0x7f9b23d67089 - start_thread
  19:     0x7f9b2388742e - __clone
  20:                0x0 - <unknown>
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:916:5
stack backtrace:
   0:     0x5603f5c83c1b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h9d1ecf383d3d35dd
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x5603f5c90ee1 - std::sys_common::backtrace::print::h377b6336f9bd7acd
                               at libstd/sys_common/backtrace.rs:68
                               at libstd/sys_common/backtrace.rs:57
   2:     0x5603f5c7d770 - std::panicking::default_hook::{{closure}}::hd8ba10fcaf3b3605
                               at libstd/panicking.rs:381
   3:     0x5603f5c7d2ac - std::panicking::default_hook::hdadaf36afc2164e8
                               at libstd/panicking.rs:397
   4:     0x5603f5c7dbbb - std::panicking::rust_panic_with_hook::h856923614f259da2
                               at libstd/panicking.rs:577
   5:     0x5603f5c7da7e - std::panicking::begin_panic::he19efc0e8b16f633
                               at libstd/panicking.rs:538
   6:     0x5603f5c7d97a - std::panicking::begin_panic_fmt::hb84c3f6aa82e7f67
                               at libstd/panicking.rs:522
   7:     0x5603f5c7d912 - rust_begin_unwind
                               at libstd/panicking.rs:498
   8:     0x5603f5ce6390 - core::panicking::panic_fmt::h87b8697e64f0b225
                               at libcore/panicking.rs:71
   9:     0x5603f5905abe - core::result::unwrap_failed::h1ad62b5dc4b86e2e
  10:     0x5603f59d4f3b - std::panicking::try::do_call::h8ce8770ad1f897e6
  11:     0x5603f5ca7f4e - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  12:     0x5603f58d9ce5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3820d78ead11dfb3
  13:     0x5603f59d5ae5 - std::panicking::try::do_call::hc6a70fb34c59ed0c
  14:     0x5603f5ca7f4e - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  15:     0x5603f598dc9a - <F as alloc::boxed::FnBox<A>>::call_box::h2ec1464b64f0c2e3
  16:     0x5603f5c8d247 - std::sys_common::thread::start_thread::hdbe346086586a07c
                               at /checkout/src/liballoc/boxed.rs:827
                               at libstd/sys_common/thread.rs:24
  17:     0x5603f5c7e228 - std::sys::unix::thread::Thread::new::thread_start::h780b8fb895b899ad
                               at libstd/sys/unix/thread.rs:90
  18:     0x7f9b23d67089 - start_thread
  19:     0x7f9b2388742e - __clone
  20:                0x0 - <unknown>

```

This is just running an unmodified version of the TodoMVC example, using the latest versions of cargo-web and stdweb.

**Comment by koute** [comment]
By `latest` do you mean latest published on `crates.io`, or the current `master` branch?

Also what is your OS, Rust version, Web browser and how are you using `cargo-web start` to launch the example?

**Comment by iirelu** [comment]
Installed cargo-web via `cargo install cargo-web`, have `stdweb = "0.3.0"` in my Cargo.toml. Manjaro, rustc 1.25.0-nightly (61452e506 2018-01-09), Chrome, and running `cargo web start --target-webasm` to start it.

**Comment by koute** [comment]
Can you try the newest `cargo-web` from `master`? I've fixed a very similar bug yesterday.

**Comment by iirelu** [comment]
Thanks, that fixes it! I should definitely remember to use the latest master when filing bug reports in the future.

**Comment by koute** [comment]
Don't worry about it, it's no problem at all. (:
