### ISSUE TITLE
Compiling in release mode fails

### ISSUE THREAD

**Issue by FliegendeWurst** [koute/stdweb#9]
I'm trying to run the todo example.

    $ cargo web start --port 8008 --release
    error: linking with `emcc` failed: exit code: 1
      |
      = note: "emcc" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib" "/tmp/stdweb/examples/todomvc/target/asmjs-unknown-emscripten/release/deps/todomvc-6fb1feda799b1a50.0.o" "-o" "/tmp/stdweb/examples/todomvc/target/asmjs-unknown-emscripten/release/deps/todomvc-6fb1feda799b1a50.js" "-s" "EXPORTED_FUNCTIONS=[\"_main\",\"_rust_eh_personality\"]" "-O3" "--memory-init-file" "0" "-g0" "-s" "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]" "-L" "/tmp/stdweb/examples/todomvc/target/asmjs-unknown-emscripten/release/deps" "-L" "/tmp/stdweb/examples/todomvc/target/release/deps" "-L" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib" "/tmp/stdweb/examples/todomvc/target/asmjs-unknown-emscripten/release/deps/libstdweb-f006930ac2288929.rlib" "/tmp/stdweb/examples/todomvc/target/asmjs-unknown-emscripten/release/deps/libserde_json-f08a34ce468f736d.rlib" "/tmp/stdweb/examples/todomvc/target/asmjs-unknown-emscripten/release/deps/libdtoa-8272a2cba0c82a0d.rlib" "/tmp/stdweb/examples/todomvc/target/asmjs-unknown-emscripten/release/deps/libnum_traits-d94c71f49a0f03a7.rlib" "/tmp/stdweb/examples/todomvc/target/asmjs-unknown-emscripten/release/deps/libserde-16cc3e2e813f4b59.rlib" "/tmp/stdweb/examples/todomvc/target/asmjs-unknown-emscripten/release/deps/libitoa-99898550fe0c9aaa.rlib" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libstd-35ad9950c7e5074b.rlib" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libpanic_unwind-fb44afc024bbc636.rlib" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libunwind-14b8f3202acdad6a.rlib" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/librand-20a50a22d4c2b1e9.rlib" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libcollections-b479831207997444.rlib" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/liballoc-10b591f1a68dd370.rlib" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libstd_unicode-f4f0ae88f5ad8ad4.rlib" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/liballoc_system-06d737faf6076d7c.rlib" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/liblibc-6ecacccb5bdc4911.rlib" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libcore-bfaa82017ca17cb2.rlib" "/home/arne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libcompiler_builtins-863b57a66ba6c3e1.rlib" "-l" "c" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1"
      = note: WARNING:root:(Emscripten: system change: 1.37.10|/home/arne/bin/clang/e1.37.13_64bit|4.0 vs 1.37.13|/home/arne/bin/clang/e1.37.13_64bit|4.0, clearing cache)
              ERROR:root:Emscripten, llvm and clang repo versions do not match, this is dangerous (1.37.10, 1.37.13, 1.37.13)
              ERROR:root:Make sure to use the same branch in each repo, and to be up-to-date on each. See http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
              INFO:root:(Emscripten: Running sanity checks)
              INFO:root:generating system library: libc.bc... (this will be cached in "/home/arne/.emscripten_cache/asmjs/libc.bc" for subsequent builds)
              INFO:root: - ok
              INFO:root:generating system library: dlmalloc.bc... (this will be cached in "/home/arne/.emscripten_cache/asmjs/dlmalloc.bc" for subsequent builds)
              INFO:root: - ok
              
              /home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272
                      throw new JS_Parse_Error(message, line, col, pos);
                      ^
              TypeError: (intermediate value) is not a function
                  at new JS_Parse_Error (/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:261:21)
                  at js_error (/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272:15)
                  at croak (/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:742:17)
                  at token_error (/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:749:17)
                  at unexpected (/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:755:17)
                  at Object.semicolon (/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:775:51)
                  at prog1 (/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1314:29)
                  at simple_statement (/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:906:35)
                  at /home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:816:35
                  at block_ (/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:999:32)
                  at /home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:821:52
              Traceback (most recent call last):
                File "/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/emcc", line 13, in <module>
                  emcc.run()
                File "/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/emcc.py", line 1982, in run
                  JSOptimizer.flush()
                File "/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/emcc.py", line 1877, in flush
                  run_passes(chunks[0], title, just_split=False, just_concat=False)
                File "/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/emcc.py", line 1850, in run_passes
                  final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
                File "/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/shared.py", line 2046, in js_optimizer
                  ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
                File "/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/js_optimizer.py", line 563, in run
                  return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
                File "/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/tempfiles.py", line 78, in run_and_clean
                  return func()
                File "/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/js_optimizer.py", line 563, in <lambda>
                  return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
                File "/home/arne/.local/share/cargo-web/emscripten/x86_64-unknown-linux-gnu/emscripten/tools/js_optimizer.py", line 502, in run_on_js
                  assert proc.returncode == 0
              AssertionError
              
    
    error: aborting due to previous error(s)
    
    error: Could not compile `todomvc`.
    
    To learn more, run the command again with --verbose.
    error: build failed

**Comment by Shnatsel** [comment]
Confirming this on `cargo build --target asmjs-unknown-emscripten --release` invocation, so it's not specific to `cargo web`

My rustc version is `rustc 1.19.0-nightly (0ed1ec9f9 2017-05-18)`

**Comment by koute** [comment]
Sorry for the delay; was on a vacation.

The problem should be fixed now. Thanks for the report!

**Comment by Shnatsel** [comment]
Thanks for the swift response! (From my perspective, anyway :smile: )

However, I still seem to be hitting this exact error even on v0.1.1 when compiling this code:

```
#[macro_use]
extern crate stdweb;

fn main() {
    stdweb::initialize();
    js! { alert!( @{"Hello, web!"} ) };
    stdweb::event_loop();
}
```

That's the entirety of my `main.rs`. Here's the error log, clearly showing stdweb updated to v0.1.1:

```
> rustup run nightly cargo build --target asmjs-unknown-emscripten --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling dtoa v0.4.1
   Compiling num-traits v0.1.39
   Compiling itoa v0.3.1
   Compiling serde v1.0.9
   Compiling serde_json v1.0.2
   Compiling stdweb v0.1.1
   Compiling hello_web v0.1.0 (file:///home/shnatsel/Code/stdweb/examples/hello_web)
error: linking with `emcc` failed: exit code: 1
  |
  = note: "emcc" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib" "/home/shnatsel/Code/stdweb/examples/hello_web/target/asmjs-unknown-emscripten/release/deps/hello_web-7c8bdd35a763e252.0.o" "-o" "/home/shnatsel/Code/stdweb/examples/hello_web/target/asmjs-unknown-emscripten/release/deps/hello_web-7c8bdd35a763e252.js" "-s" "EXPORTED_FUNCTIONS=[\"_main\",\"_rust_eh_personality\"]" "-O3" "--memory-init-file" "0" "-g0" "-s" "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]" "-L" "/home/shnatsel/Code/stdweb/examples/hello_web/target/asmjs-unknown-emscripten/release/deps" "-L" "/home/shnatsel/Code/stdweb/examples/hello_web/target/release/deps" "-L" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib" "/home/shnatsel/Code/stdweb/examples/hello_web/target/asmjs-unknown-emscripten/release/deps/libstdweb-ce587d8a742f0269.rlib" "/home/shnatsel/Code/stdweb/examples/hello_web/target/asmjs-unknown-emscripten/release/deps/libserde_json-f08a34ce468f736d.rlib" "/home/shnatsel/Code/stdweb/examples/hello_web/target/asmjs-unknown-emscripten/release/deps/libdtoa-8272a2cba0c82a0d.rlib" "/home/shnatsel/Code/stdweb/examples/hello_web/target/asmjs-unknown-emscripten/release/deps/libnum_traits-d94c71f49a0f03a7.rlib" "/home/shnatsel/Code/stdweb/examples/hello_web/target/asmjs-unknown-emscripten/release/deps/libserde-c82bbb299be6eed6.rlib" "/home/shnatsel/Code/stdweb/examples/hello_web/target/asmjs-unknown-emscripten/release/deps/libitoa-99898550fe0c9aaa.rlib" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libstd-35ad9950c7e5074b.rlib" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/librand-20a50a22d4c2b1e9.rlib" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libcollections-b479831207997444.rlib" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libstd_unicode-f4f0ae88f5ad8ad4.rlib" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libpanic_unwind-fb44afc024bbc636.rlib" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libunwind-14b8f3202acdad6a.rlib" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/liballoc-10b591f1a68dd370.rlib" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/liballoc_system-06d737faf6076d7c.rlib" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/liblibc-6ecacccb5bdc4911.rlib" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libcore-bfaa82017ca17cb2.rlib" "/home/shnatsel/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libcompiler_builtins-863b57a66ba6c3e1.rlib" "-l" "c" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1"
  = note: 
          /home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272
                  throw new JS_Parse_Error(message, line, col, pos);
                  ^
          TypeError: (intermediate value) is not a function
              at new JS_Parse_Error (/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:261:21)
              at js_error (/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272:15)
              at croak (/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:742:17)
              at token_error (/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:749:17)
              at unexpected (/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:755:17)
              at Object.semicolon (/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:775:51)
              at prog1 (/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1314:29)
              at simple_statement (/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:906:35)
              at /home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:816:35
              at block_ (/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:999:32)
          Traceback (most recent call last):
            File "/home/shnatsel/Code/emsdk_portable/emscripten/incoming/emcc", line 13, in <module>
              emcc.run()
            File "/home/shnatsel/Code/emsdk_portable/emscripten/incoming/emcc.py", line 1997, in run
              JSOptimizer.flush()
            File "/home/shnatsel/Code/emsdk_portable/emscripten/incoming/emcc.py", line 1890, in flush
              run_passes(chunks[0], title, just_split=False, just_concat=False)
            File "/home/shnatsel/Code/emsdk_portable/emscripten/incoming/emcc.py", line 1863, in run_passes
              final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
            File "/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/shared.py", line 2046, in js_optimizer
              ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
            File "/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 563, in run
              return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
            File "/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 78, in run_and_clean
              return func()
            File "/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 563, in <lambda>
              return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
            File "/home/shnatsel/Code/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 502, in run_on_js
              assert proc.returncode == 0
          AssertionError
          

error: aborting due to previous error

error: Could not compile `hello_web`.
```

Am I doing something wrong or there are leftover `let`s in there somewhere?

**Comment by koute** [comment]
@Shnatsel Change the `alert!` into `alert` and it will work. (:

Unfortunately the error message produced by the compiler here is far from helpful; it will spew out this error every time it encounters a syntax error in the inlined JavaScript code.

**Comment by Shnatsel** [comment]
Oh dang. Thanks!
